package com.oierbravo.create_mechanical_template.infrastructure.data;

import com.oierbravo.create_mechanical_template.foundation.data.recipe.CraftingRecipeGen;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.PackOutput;
import net.minecraftforge.data.event.GatherDataEvent;

public class ModDataGen {
    public static void gatherData(GatherDataEvent event) {

        DataGenerator generator = event.getGenerator();
        PackOutput output = generator.getPackOutput();

        if (event.includeServer()) {
            generator.addProvider(true, new CraftingRecipeGen(output));
        }
    }
}
